export const chatConstants = {
    ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
    ADD_MESSAGE_FAILURE: 'ADD_MESSAGE_FAILURE',
    
    RECEIVED_MESSAGE: 'RECEIVED_MESSAGE',    

    GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE'
};
